name: lime-license

on:
  pull_request:
    branches: [ master ]

jobs:
  license-header:
    runs-on: ubuntu-latest
    container:
      image: opensauce04/lime3ds-build:latest
      options: -u 1001
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch master branch
        run: git fetch origin master:master
      - name: Check license headers
        run: ./.ci/license-header.rb
