name: lime-license

on:
  pull_request:
    branches: [ master ]

jobs:
  license-header:
    runs-on: ubuntu-latest
    container:
      image: opensauce04/lime3ds-build:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check license headers
        run: ./.ci/license-header.rb
