// Copyright 2016 Citra Emulator Project
// Licensed under GPLv2 or any later version
// Refer to the license.txt file included.

#include "common/archives.h"
#include "core/hle/service/ac/ac_i.h"

namespace Service::AC {

AC_I::AC_I(std::shared_ptr<Module> ac) : Module::Interface(std::move(ac), "ac:i", 10) {
    static const FunctionInfo functions[] = {
        // clang-format off
        {0x0001, &AC_I::CreateDefaultConfig, "CreateDefaultConfig"},
        {0x0004, &AC_I::ConnectAsync, "ConnectAsync"},
        {0x0005, &AC_I::GetConnectResult, "GetConnectResult"},
        {0x0007, &AC_I::CancelConnectAsync, "CancelConnectAsync"},
        {0x0008, &AC_I::CloseAsync, "CloseAsync"},
        {0x0009, &AC_I::GetCloseResult, "GetCloseResult"},
        {0x000A, nullptr, "GetLastErrorCode"},
        {0x000C, &AC_I::GetStatus, "GetStatus"},
        {0x000D, &AC_I::GetWifiStatus, "GetWifiStatus"},
        {0x000E, &AC_I::GetCurrentAPInfo, "GetCurrentAPInfo"},
        {0x000F, &AC_I::GetConnectingInfraPriority, "GetConnectingInfraPriority"},
        {0x0010, nullptr, "GetCurrentNZoneInfo"},
        {0x0011, nullptr, "GetNZoneApNumService"},
        {0x001D, nullptr, "ScanAPs"},
        {0x0024, nullptr, "AddDenyApType"},
        {0x0027, &AC_I::GetInfraPriority, "GetInfraPriority"},
        {0x002C, &AC_I::SetFromApplication, "SetFromApplication"},
        {0x002D, &AC_I::SetRequestEulaVersion, "SetRequestEulaVersion"},
        {0x002F, &AC_I::GetNZoneBeaconNotFoundEvent, "GetNZoneBeaconNotFoundEvent"},
        {0x0030, &AC_I::RegisterDisconnectEvent, "RegisterDisconnectEvent"},
        {0x0036, &AC_I::GetConnectingProxyEnable, "GetConnectingProxyEnable"},
        {0x003C, nullptr, "GetAPSSIDList"},
        {0x003E, &AC_I::IsConnected, "IsConnected"},
        {0x0040, &AC_I::SetClientVersion, "SetClientVersion"},
    //exclusive to AC:I service
	{0x0401, nullptr, "LoadNetworkSetting"},
	{0x0402, nullptr, "UpdateNetworkSetting"},
	{0x0403, nullptr, "RemoveNetworkSetting"},
	{0x0404, nullptr, "FlushNetworkSetting"},
	{0x0405, nullptr, "ConvertNetworkSettingNdsTo3ds"},
	{0x0406, nullptr, "InitializeNetworkSetting"},
	{0x0407, nullptr, "GetNetworkSettingVersion"},
	{0x0408, nullptr, "SetNetworkSettingVersion"},
	{0x0409, nullptr, "GetNetworkSetting_Crc"},
	{0x040A, nullptr, "SetNetworkSetting_Crc"},
	{0x040B, nullptr, "GetNetworkWirelessEnable"},
	{0x040C, nullptr, "SetNetworkWirelessEnable"},
	{0x040D, nullptr, "GetNetworkWirelessEditableEssidSecurity"},
	{0x040E, nullptr, "SetNetworkWirelessEditableEssidSecurity"},
	{0x040F, nullptr, "GetNetworkWirelessEssidSecuritySsid"},
	{0x0410, nullptr, "SetNetworkWirelessEssidSecuritySsid"},
	{0x0411, nullptr, "GetNetworkWireleesEssidSsidLength"},
	{0x0412, nullptr, "SetNetworkWirelessEssidSsidLength"},
	{0x0413, nullptr, "GetNetworkWirelessEssidSecurityMode"},
	{0x0414, nullptr, "SetNetworkWirelessEssidSecurityMode"},
	{0x0415, nullptr, "GetNetworkWirelessEssidPassphrase"},
	{0x0416, nullptr, "SetNetworkWirelessEssidPassphrase"},
	{0x4170, nullptr, "GetNetworkWirelessEssidSecurityKey"},
	{0x0418, nullptr, "SetNetworkWirelessEssidSecurityKey"},
	{0x0419, nullptr, "GetNetworkMultiSSIDEnable"},
	{0x041A, nullptr, "SetNetworkMultiSSIDEnable"},
	{0x041B, nullptr, "GetNetworkWirelesMultiSsidMultiSsidType"},
	{0x041C, nullptr, "SetNetworkWirelesMultiSsidMultiSsidType"},
	{0x041D, nullptr, "GetNetworkWirelessMultiSsidSettingNum"},
	{0x041E, nullptr, "SetNetworkWirelessMultiSsidSettingNum"},
	{0x041F, nullptr, "GetNetworkWirelessMultiSsidSetting0Ssid"},
	{0x0420, nullptr, "SetNetworkWirelessMultiSsidSetting0Ssid"},
	{0x0421, nullptr, "GetNetworkWirelessMultiSsidSetting0SsidLength"},
	{0x0422, nullptr, "Unknown_0422"},
	{0x0424, nullptr, "Unknown_0424"},
	{0x0425, nullptr, "GetNetworkWirelessMultiSsidSetting0PassPhrase"},
	{0x0426, nullptr, "Unknown_0426"},
	{0x0427, nullptr, "GetNetworkWirelessMultiSsidSetting0Key"},
	{0x0428, nullptr, "SetNetworkWirelessMultiSsidSetting0Key"},
	{0x0429, nullptr, "GetNetworkMultiSsidSetting1Ssid"},
	{0x042A, nullptr, "SetNetworkMultiSsidSetting1Ssid"},
	{0x042B, nullptr, "GetNetworkMultiSsidSetting1SsidLength"},
	{0x042C, nullptr, "Unknown_042C"},
	{0x042E, nullptr, "Unknown_042E"},
	{0x042F, nullptr, "GetNetworkWirelessMultiSsidSetting1PassPhrase"},
	{0x0430, nullptr, "Unknown_0430"},
	{0x0431, nullptr, "GetNetworkWirelessMultiSsidSetting1Key"},
	{0x0432, nullptr, "SetNetworkWirelessMultiSsidSetting1Key"},
	{0x0433, nullptr, "GetNetworkWirelessMultiSsidSetting2Ssid"},
	{0x0434, nullptr, "SetNetworkWirelessMultiSsidSetting2Ssid"},
	{0x0436, nullptr, "Unknown_0436"},
	{0x0438, nullptr, "Unknown_0438"},
	{0x0439, nullptr, "GetNetworkWirelessMultiSsidSetting2Passphrase"},
	{0x043A, nullptr, "Unknown_043A"},
	{0x043B, nullptr, "GetNetworkWirelessMultiSsidSetting2Key"},
	{0x043C, nullptr, "SetNetworkWirelessMultiSsidSetting2Key"},
	{0x043D, nullptr, "GetNetworkWirelessMultiSsidSetting3Ssid"},
	{0x043E, nullptr, "SetNetworkWirelessMultiSsidSetting3Ssid"},
	{0x0444, nullptr, "Unknown_0444"},
	{0x0445, nullptr, "GetNetworkWirelessMultiSsidSetting3Key"},
	{0x0446, nullptr, "SetNetworkWirelessMultiSsidSetting3Key"},
	{0x0447, nullptr, "GetNetworkIpEnableDHCP"},
	{0x0448, nullptr, "SetNetworkIpEnableDHCP"},
	{0x0449, nullptr, "GetNetworkAutoDNSSetting"},
	{0x044A, nullptr, "SetNetworkAutoDNSSetting"},
	{0x044B, nullptr, "GetNetworkIpAddress"},
	{0x044C, nullptr, "SetNetworkIpAddress"},
	{0x044D, nullptr, "GetNetworkDefaultGateway"},
	{0x044E, nullptr, "SetNetworkDefaultGateway"},
	{0x044F, nullptr, "GetNetworkIpNetmask"},
	{0x0450, nullptr, "SetNetworkIpNetMask"},
	{0x0451, nullptr, "GetNetworkIpPrimaryDNS"},
	{0x0452, nullptr, "SetNetworkIpPrimaryDNS"},
	{0x0453, nullptr, "GetNetworkIpSecondaryDNS"},
	{0x0454, nullptr, "SetNetworkIpSecondaryDNS"},
	{0x0455, nullptr, "GetNetworkIpScanlessConnectHasConnected"},
	{0x0456, nullptr, "SetNetworkIpScanlessConnectHasConnected"},
	{0x0459, nullptr, "GetNetworkIpScanlessConnectLastConnectedBssid"},
	{0x045A, nullptr, "SetNetworkIpScanlessConnectLastConnectedBssid"},
	{0x045F, nullptr, "GetNetworkProxyEnable"},
	{0x0460, nullptr, "SetNetworkProxyEnable"},
	{0x0461, nullptr, "GetNetworkProxyAuthType"},
	{0x0462, nullptr, "SetNetworkProxyAuthType"},
	{0x0463, nullptr, "GetNetworkProxyPort"},
	{0x0464, nullptr, "SetNetworkProxyPort"},
	{0x0465, nullptr, "GetNetworkProxyHost"},
	{0x0466, nullptr, "SetNetworkProxyHost"},
	{0x0467, nullptr, "GetNetworkSettingProxyUserName"},
	{0x0468, nullptr, "SetNetworkSettingProxyUserName"},
	{0x0469, nullptr, "GetNetworkSettingProxyPassword"},
	{0x046A, nullptr, "SetNetworkSettingProxyPassword"},
	{0x046B, nullptr, "GetNetworkEnableUPnP"},
	{0x046C, nullptr, "SetNetworkEnableUPnP"},
	{0x046D, nullptr, "GetNetworkOtherMtu"},
	{0x046E, nullptr, "SetNetworkOtherMtu"},
	{0x046F, nullptr, "GetConnectingNetworkSettingVersion(?)"},
	{0x0470, nullptr, "GetConnectingNetworkCrc"},
	{0x0471, nullptr, "GetConnectingNetworkWirelessEnable"},
	{0x0473, nullptr, "GetConnectingNetworkWirelessEssidSsid"},
	{0x0477, nullptr, "GetConnectingNetworkWirelessEssidSecurityKey"},
	{0x0478, nullptr, "GetConnectingNetworkMultiSsidEnable"},
	{0x048F, nullptr, "GetConnectingNetworkEnableDHCP"},
	{0x0490, nullptr, "GetConnectingNetworkIpAutoDNSSetting"},
	{0x0491, nullptr, "GetConnectingNetworkIpAddress"},
	{0x0492, nullptr, "GetConnectingNetworkIpDefaultGateway"},
	{0x0493, nullptr, "GetConnectingNetworkIpNetmask"},
	{0x0494, nullptr, "GetConnectingNetworkPrimaryDNS"},
	{0x0495, nullptr, "GetConnectingNetworkSecondaryDNS"},
	{0x049B, nullptr, "GetConnectingNetworkProxyEnable"},
	{0x049C, nullptr, "GetConnectingNetworkProxyAuthType"},
	{0x049D, nullptr, "GetConnectingNetworkProxyPort"},
	{0x049E, nullptr, "GetConnectingNetworkProxyHost"},
	{0x049F, nullptr, "GetConnectingNetworkProxyUserName"},
	{0x04A0, nullptr, "GetConnectingNetworkProxyPassword"},
	{0x04A1, nullptr, "GetConnectingNetworkEnableUPnP"},
	{0x04A2, nullptr, "GetConnectingNetworkMtu"},
        // clang-format on
    };
    RegisterHandlers(functions);
}

} // namespace Service::AC

SERIALIZE_EXPORT_IMPL(Service::AC::AC_I)
